import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import {initializeAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged,setPersistence,browserSessionPersistence} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import {getFirestore,doc,getDoc,collection,query,where,onSnapshot} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const TIP_CONFIG={apiKey:'AIzaSyB7yIl1T6ufniDAhed1vGNzi8c1d-ghfFI',authDomain:'juicy-tip-all-in-one.firebaseapp.com',projectId:'juicy-tip-all-in-one',storageBucket:'juicy-tip-all-in-one.firebasestorage.app',messagingSenderId:'1018030638724',appId:'1:1018030638724:web:19b945d908229f622664d1'};
const BOARD_ROOT='https://table-live-by-iwanto-zhang-default-rtdb.firebaseio.com/juicyTableLive/JUICY-HUNTSVILLE/flexibleFloorV1';
const app=initializeApp(TIP_CONFIG),auth=initializeAuth(app,{persistence:browserSessionPersistence}),db=getFirestore(app);
const authReady=(async()=>{try{if(typeof auth.authStateReady==='function')await auth.authStateReady();await setPersistence(auth,browserSessionPersistence)}catch(e){console.warn('Auth initialization:',e)}})();
const $=id=>document.getElementById(id),num=v=>Number(v)||0,txt=v=>String(v??''),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const money=v=>'$'+num(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}),n1=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:1});
const esc=s=>txt(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const iso=d=>{const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`},today=()=>iso(new Date());
const slug=s=>txt(s).trim().toLowerCase().replace(/[^a-z0-9._-]/g,''),emailFor=u=>{const v=txt(u).trim().toLowerCase();return v.includes('@')?v:`${slug(v)}@juicytip.app`};
const normName=s=>txt(s).trim().replace(/\s+/g,' '),idKey=s=>normName(s).toLowerCase();

let profile=null,tipUnsubs=[],timer=null,tipFeed={reports:false,batches:false,error:false};
let state={mode:'daily',tab:'overview',from:today(),to:today(),shift:'ALL',board:[],boardRoster:[],tips:[],batches:[],tipRoster:[],rows:[],rawNames:[],analysis:null};

const DEFAULT_ID={
 'a.j.':{canonical:'Ariana Garner',active:true},'a.j':{canonical:'Ariana Garner',active:true},'aj':{canonical:'Ariana Garner',active:true},
 'ariana garner':{canonical:'Ariana Garner',active:true},'ariana graner':{canonical:'Ariana Garner',active:true},
 'alaina montalvo':{canonical:'Alainna Montalvo',active:true},'alainna montalvo':{canonical:'Alainna Montalvo',active:true},'alainna':{canonical:'Alainna Montalvo',active:true},
 'aida':{canonical:'Aida Gonzales',active:false},'aida gonzales':{canonical:'Aida Gonzales',active:false}
};
function loadIdentity(){let stored={};try{stored=JSON.parse(localStorage.getItem('fzsi_identity_v12')||localStorage.getItem('fzsi_identity_v11')||localStorage.getItem('fzsi_identity_v1')||'{}')||{}}catch(e){}const merged={...DEFAULT_ID,...stored};for(const k of ['a.j.','a.j','aj','ariana garner','ariana graner'])merged[k]={canonical:'Ariana Garner',active:true};return merged}
let identity=loadIdentity();
function canonical(s){const n=normName(s);return identity[idKey(n)]?.canonical||n||'Unknown'}
function isActiveName(s){const x=identity[idKey(s)]||identity[idKey(canonical(s))];return x?.active!==false}
function saveIdentity(){localStorage.setItem('fzsi_identity_v12',JSON.stringify(identity))}

function dateList(a,b){const out=[],d=new Date(a+'T12:00:00'),end=new Date(b+'T12:00:00');while(d<=end){out.push(iso(d));d.setDate(d.getDate()+1)}return out}
function setMode(mode){state.mode=mode;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode));const d=new Date();if(mode==='daily'){state.from=state.to=today()}else if(mode==='weekly'){const x=new Date();const day=x.getDay()||7;x.setDate(x.getDate()-day+1);state.from=iso(x);x.setDate(x.getDate()+6);state.to=iso(x)}else if(mode==='monthly'){state.from=iso(new Date(d.getFullYear(),d.getMonth(),1));state.to=iso(new Date(d.getFullYear(),d.getMonth()+1,0))}syncInputs();subscribeTips();refreshBoard()}
function syncInputs(){$('from').value=state.from;$('to').value=state.to;$('shift').value=state.shift}

async function fetchJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('Board HTTP '+r.status);return r.json()}
function turnArray(x,len=60){if(Array.isArray(x))return x;const a=Array(len).fill(null);Object.entries(x||{}).forEach(([k,v])=>{if(/^\d+$/.test(k))a[+k]=v});return a}
function rowsArray(x){if(Array.isArray(x))return x;const a=Array(20).fill(null);Object.entries(x||{}).forEach(([k,v])=>{if(/^\d+$/.test(k))a[+k]=v});return a}
function epoch(entryId){const m=txt(entryId).match(/^seat_(\d{13})_/);return m?+m[1]:0}
function boardEvents(raw,date,shift){const ev=[];rowsArray(raw?.rows).forEach((r,ri)=>{if(!r)return;turnArray(r.turns).forEach((t,ti)=>{if(!t||t.skipped||!t.table)return;const p=Math.max(0,parseInt(t.people)||0),ts=epoch(t.entryId||t.partyId);ev.push({source:'LIVE',date,shift,server:canonical(r.server||'Unknown'),rawServer:normName(r.server||'Unknown'),section:txt(r.section),table:txt(t.table),people:p,rotationSlots:Math.max(1,Math.ceil(Math.max(1,p)/4)),seatedAt:ts,row:ri,turn:ti})})});return ev}
function archiveEvents(snap,date,shift){const arr=Array.isArray(snap?.events)?snap.events:Object.values(snap?.events||{});return arr.filter(Boolean).map(e=>({...e,date:e.date||date,shift:e.shift||shift,source:'ARCHIVE',server:canonical(e.server),rawServer:normName(e.server),people:num(e.people),rotationSlots:Math.max(1,num(e.rotationSlots)||Math.ceil(Math.max(1,num(e.people))/4))}))}
function boardRosterFromBoard(raw,date,shift){const out=[];rowsArray(raw?.rows).forEach((r,ri)=>{if(!r||!normName(r.server)||r.active===false||r.cutAt)return;out.push({date,shift,server:canonical(r.server),rawServer:normName(r.server),section:txt(r.section),workShift:txt(r.workShift||shift),row:ri,source:'BOARD LIVE'})});return out}
function teamShiftPeriods(v){const s=txt(v).toUpperCase();if(s.includes('DOUBLE'))return ['AM','PM'];if(s==='AM'||(s.includes('10:45')&&s.includes('2')))return ['AM'];if(s==='PM'||s.includes('LONG')||s.includes('2 PM')||s.includes('2–4')||s.includes('2-4'))return ['PM'];return ['AM','PM']}
function boardTeamRoster(raw,date){const arr=Array.isArray(raw)?raw:Object.values(raw&&typeof raw==='object'?raw:{}),out=[];arr.filter(Boolean).forEach((m,i)=>{const name=normName(m.name||m.server||m.employee);if(!name)return;const role=txt(m.position||m.role||'Server');if(role&&!/server/i.test(role))return;for(const sh of teamShiftPeriods(m.shift||m.workShift)){if(state.shift!=='ALL'&&state.shift!==sh)continue;out.push({date,shift:sh,server:canonical(name),rawServer:name,section:'',workShift:txt(m.shift||sh),row:i,source:'BOARD TEAM'})}});return out}
function dedupeRoster(items){const seen=new Set(),out=[];for(const x of items){const k=[x.date,x.shift,idKey(x.server),x.source].join('|');if(seen.has(k))continue;seen.add(k);out.push(x)}return out}

function reportName(r){return normName(r?.employee||r?.employeeDisplayName||r?.name||r?.personName)}
function reportPosition(r){return txt(r?.position||r?.role||r?.employeeSheetRow?.role||r?.employeeSheetRow?.position)}
function batchTeamMembers(batch){const team=Array.isArray(batch?.team)?batch.team:Object.values(batch?.team&&typeof batch.team==='object'?batch.team:{});return team.filter(Boolean).map(member=>{const name=normName(typeof member==='string'?member:(member?.name||member?.employee||member?.server));const role=txt(typeof member==='object'?(member?.position||member?.role):'');return {name,role}}).filter(x=>x.name)}
function batchDraftRole(batch,name){const d=batch?.drafts?.[name]||{};return txt(d?.position||d?.role||d?.employeeSheetRawRow?.role||d?.employeeSheetRawRow?.position||d?.employeeSheetFinalRow?.role||d?.employeeSheetFinalRow?.position)}
function tipRosterFromBatches(batches){
 const out=[];
 for(const b of batches||[]){const date=txt(b.date||b.id);if(!date||date<state.from||date>state.to)continue;const seen=new Set();
  /* V1.2: only the CURRENT team array is roster truth. Old draft rows are not allowed to resurrect a deleted employee. */
  for(const member of batchTeamMembers(b)){const role=member.role||batchDraftRole(b,member.name);if(role&&!/server/i.test(role))continue;const c=canonical(member.name),key=idKey(c);if(seen.has(key))continue;seen.add(key);out.push({date,server:c,rawServer:member.name,role:role||'Server',source:'TIP TEAM'})}
 }
 return out
}
function updateTipStatus(){const el=$('tipStatus');if(!el)return;if(tipFeed.error&&!(tipFeed.reports||tipFeed.batches))el.textContent='ERROR';else if(tipFeed.reports&&tipFeed.batches)el.textContent='LIVE';else if(tipFeed.reports||tipFeed.batches)el.textContent='PARTIAL';else el.textContent='SYNCING'}
async function refreshBoard(){try{$('boardStatus').textContent='SYNCING';const [arc,boards,teamDays]=await Promise.all([fetchJson(BOARD_ROOT+'/analyticsV1.json'),fetchJson(BOARD_ROOT+'/rotationBoardV31.json'),fetchJson(BOARD_ROOT+'/teamDayV1.json').catch(()=>null)]);const events=[],roster=[];for(const d of dateList(state.from,state.to)){roster.push(...boardTeamRoster(teamDays?.[d],d));for(const sh of ['AM','PM']){if(state.shift!=='ALL'&&state.shift!==sh)continue;const key=d+'_'+sh,live=boards?.[key],a=arc?.[key];if(live)roster.push(...boardRosterFromBoard(live,d,sh));const liveEv=live?boardEvents(live,d,sh):[];if(liveEv.length)events.push(...liveEv);else if(a)events.push(...archiveEvents(a,d,sh))}}state.board=events;state.boardRoster=dedupeRoster(roster);state.tipRoster=tipRosterFromBatches(state.batches);$('boardStatus').textContent='LIVE';rebuild()}catch(e){console.error(e);$('boardStatus').textContent='ERROR';rebuild()}}
function subscribeTips(){for(const u of tipUnsubs){try{u()}catch(e){}}tipUnsubs=[];tipFeed={reports:false,batches:false,error:false};updateTipStatus();if(!auth.currentUser||!profile)return;try{const qr=query(collection(db,'hourlyReports'),where('date','>=',state.from),where('date','<=',state.to));tipUnsubs.push(onSnapshot(qr,s=>{state.tips=s.docs.map(d=>({id:d.id,...d.data()}));tipFeed.reports=true;updateTipStatus();rebuild()},e=>{console.error(e);tipFeed.error=true;updateTipStatus()}));const qb=query(collection(db,'hourlyV1Batches'),where('date','>=',state.from),where('date','<=',state.to));tipUnsubs.push(onSnapshot(qb,s=>{state.batches=s.docs.map(d=>({id:d.id,...d.data()}));state.tipRoster=tipRosterFromBatches(state.batches);tipFeed.batches=true;updateTipStatus();rebuild()},e=>{console.warn('Tip roster feed unavailable:',e);tipFeed.error=true;updateTipStatus()}))}catch(e){console.error(e);tipFeed.error=true;updateTipStatus()}}

function reportHours(r){return num(r.totalHoursWork??r.totalHours??r.hoursWorked??r.hours?.totalHours??(num(r.totalMinutesWork)/60))}
function shiftBucket(r){const s=txt(r.shift).toUpperCase();if(s==='AM'||s.includes('10:45 - 14:00'))return 'AM';if(s==='PM'||s.includes('14:00 - 16:00'))return 'PM';return 'ALL'}
function reportSales(r){return num(r.grandTotal)}
function reportTip(r){return num(r.grandTotalTip??(num(r.paidTip)+num(r.cashTip)))}
function reportPayout(r){return num(r.totalPaidOut??r.grandTotalAfterAdjustment??r.finalPaidOut)}
function reportBusser(r){return num(r.busserTipOut??r.busserTotal??num(r.busserTipOutAM)+num(r.busserTipOutPM))}
function reportBarOut(r){return num(r.barTipOut??r.totalBarTipOut??num(r.barTipOutAM)+num(r.barTipOut24)+num(r.barTipOutPM))}
function reportBarIn(r){return num(r.bartenderBarTipReceived??r.barTipReceived??num(r.barTipReceivedAM)+num(r.barTipReceived24)+num(r.barTipReceivedPM))}
function median(vals){const a=vals.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function medianGap(events){const byDayShift=new Map();for(const e of events){const k=e.date+'|'+e.shift;if(!byDayShift.has(k))byDayShift.set(k,[]);if(num(e.seatedAt))byDayShift.get(k).push(num(e.seatedAt))}const gaps=[];for(const arr of byDayShift.values()){arr.sort((a,b)=>a-b);for(let i=1;i<arr.length;i++){const m=(arr[i]-arr[i-1])/60000;if(m>0&&m<240)gaps.push(m)}}return median(gaps)}
function minMaxScore(vals,v,{inverse=false}={}){const a=vals.filter(x=>Number.isFinite(x));if(!a.length||!Number.isFinite(v))return null;const lo=Math.min(...a),hi=Math.max(...a);if(Math.abs(hi-lo)<1e-9)return 100;let s=(v-lo)/(hi-lo)*100;if(inverse)s=100-s;return clamp(s,0,100)}
function weighted(parts){let sum=0,w=0;for(const [v,weight] of parts){if(v==null||!Number.isFinite(v))continue;sum+=v*weight;w+=weight}return w?sum/w:null}
function scoreClass(v){return v==null?'':v>=70?'high':v>=45?'mid':'low'}

function rosterIntersectionNames(){const board=new Set(state.boardRoster.map(r=>r.date+'|'+idKey(r.server))),tip=new Set(state.tipRoster.map(r=>r.date+'|'+idKey(r.server))),names=new Set();for(const k of board){if(tip.has(k))names.add(k.split('|').slice(1).join('|'))}return names}
function buildRows(){
 const map=new Map(),get=(n,meta={})=>{n=canonical(n);if(!map.has(n))map.set(n,{name:n,active:isActiveName(n),events:[],reports:[],tables:0,guests:0,rotation:0,hours:0,sales:0,paidTip:0,cashTip:0,tipIncome:0,payout:0,busser:0,barOut:0,barIn:0,days:new Set(),am:0,pm:0,sources:new Set(),aliases:new Set(),scheduled:false});const x=map.get(n);if(meta.source)x.sources.add(meta.source);if(meta.raw)x.aliases.add(meta.raw);if(meta.scheduled)x.scheduled=true;if(meta.date)x.days.add(meta.date);return x};
 const rosterBoth=rosterIntersectionNames();
 /* No-activity roster rows only appear when Board AND Tip currently agree. This prevents deleted Mia/stale draft resurrection. */
 for(const r of state.boardRoster){if(rosterBoth.has(idKey(r.server)))get(r.server,{source:r.source,raw:r.rawServer,scheduled:true,date:r.date})}
 for(const r of state.tipRoster){if(rosterBoth.has(idKey(r.server)))get(r.server,{source:r.source,raw:r.rawServer,scheduled:true,date:r.date})}
 for(const e of state.board){const x=get(e.server,{source:'BOARD',raw:e.rawServer,date:e.date});x.events.push(e);x.tables++;x.guests+=num(e.people);x.rotation+=num(e.rotationSlots);x.days.add(e.date);if(e.shift==='AM')x.am++;if(e.shift==='PM')x.pm++}
 const boardIds=new Set([...state.board.map(e=>e.server),...state.boardRoster.map(r=>r.server)]);
 for(const r of state.tips){const n=reportName(r);if(!n)continue;const c=canonical(n),pos=reportPosition(r);if(pos&&!/server/i.test(pos))continue;if(!pos&&!boardIds.has(c))continue;const bucket=shiftBucket(r);if(state.shift!=='ALL'&&bucket!=='ALL'&&bucket!==state.shift)continue;if(state.shift!=='ALL'&&bucket==='ALL')continue;const x=get(c,{source:'TIP REPORT',raw:n,date:r.date});x.reports.push(r);x.days.add(r.date);x.hours+=reportHours(r);x.sales+=reportSales(r);x.paidTip+=num(r.paidTip);x.cashTip+=num(r.cashTip);x.tipIncome+=reportTip(r);x.payout+=reportPayout(r);x.busser+=reportBusser(r);x.barOut+=reportBarOut(r);x.barIn+=reportBarIn(r)}
 let rows=[...map.values()];
 rows.forEach(x=>{x.daysCount=x.days.size;x.avgParty=x.tables?x.guests/x.tables:0;x.salesPerGuest=x.guests?x.sales/x.guests:0;x.salesPerTable=x.tables?x.sales/x.tables:0;x.tablesPerHour=x.hours?x.tables/x.hours:0;x.guestsPerHour=x.hours?x.guests/x.hours:0;x.salesPerHour=x.hours?x.sales/x.hours:0;x.tipPerHour=x.hours?x.tipIncome/x.hours:0;x.tipPerGuest=x.guests?x.tipIncome/x.guests:0;x.rotationPerHour=x.hours?x.rotation/x.hours:0;x.guestsPerRotation=x.rotation?x.guests/x.rotation:0;x.tablesPerRotation=x.rotation?x.tables/x.rotation:0;x.medianSeatGap=medianGap(x.events);x.hasBoardActivity=!!(x.tables||x.guests);x.hasTipReport=x.reports.length>0;x.dataComplete=!!(x.hasBoardActivity&&x.hasTipReport&&x.hours>0&&x.sales>0);x.dataQuality=(x.hasBoardActivity?50:0)+(x.hasTipReport&&x.hours>0?25:0)+(x.hasTipReport&&x.sales>0?25:0);x.hasPerformance=x.hasBoardActivity||x.hasTipReport});
 const eligible=rows.filter(x=>x.dataComplete);
 const vals=k=>eligible.map(r=>r[k]);
 for(const x of rows){if(!x.dataComplete){x.paceScore=x.salesScore=x.tipScore=x.overall=null;continue}const gapScore=x.medianSeatGap?minMaxScore(vals('medianSeatGap'),x.medianSeatGap,{inverse:true}):null;x.paceScore=weighted([[minMaxScore(vals('tablesPerHour'),x.tablesPerHour),.45],[minMaxScore(vals('guestsPerHour'),x.guestsPerHour),.35],[gapScore,.20]]);x.salesScore=weighted([[minMaxScore(vals('salesPerHour'),x.salesPerHour),.50],[minMaxScore(vals('salesPerGuest'),x.salesPerGuest),.30],[minMaxScore(vals('salesPerTable'),x.salesPerTable),.20]]);x.tipScore=weighted([[minMaxScore(vals('tipPerHour'),x.tipPerHour),.65],[minMaxScore(vals('tipPerGuest'),x.tipPerGuest),.35]]);x.overall=weighted([[x.paceScore,.40],[x.salesScore,.40],[x.tipScore,.20]])}
 const totalGuests=rows.reduce((a,x)=>a+x.guests,0),totalRotation=rows.reduce((a,x)=>a+x.rotation,0);for(const x of rows){x.guestShare=totalGuests?x.guests/totalGuests:0;x.rotationShare=totalRotation?x.rotation/totalRotation:0;x.rotationDeltaPct=(x.guestShare-x.rotationShare)*100}
 rows=rows.filter(x=>x.hasPerformance||x.scheduled).sort((a,b)=>(b.dataComplete-a.dataComplete)||num(b.overall)-num(a.overall)||b.sales-a.sales||b.guests-a.guests||a.name.localeCompare(b.name));
 return rows
}
function totals(rows){return rows.reduce((a,x)=>{a.tables+=x.tables;a.guests+=x.guests;a.rotation+=x.rotation;a.hours+=x.hours;a.sales+=x.sales;a.tip+=x.tipIncome;a.payout+=x.payout;return a},{tables:0,guests:0,rotation:0,hours:0,sales:0,tip:0,payout:0})}
function groupFairness(rows){const active=rows.filter(x=>x.rotation>0||x.guests>0),tr=active.reduce((a,x)=>a+x.rotation,0),tg=active.reduce((a,x)=>a+x.guests,0);if(!tr||!tg)return null;const tv=.5*active.reduce((a,x)=>a+Math.abs(x.rotation/tr-x.guests/tg),0);return clamp((1-tv)*100,0,100)}
function peerMedian(rows,key){return median(rows.filter(x=>x.dataComplete).map(x=>x[key]))}
function diagnose(row,rows,lang='EN'){
 const id=lang==='ID',causes=[],actions=[];
 if(!row.dataComplete){return {status:'DATA INCOMPLETE',causes:[id?'Data Board + Tip belum lengkap untuk membuat penilaian yang adil.':'Board + Tip data are not complete enough for a fair performance rating.'],actions:[id?'Finalisasi laporan Tip/jam kerja dan pastikan seating Board sudah tersinkron sebelum menilai server.':'Finalize the Tip/hours report and confirm Board seating sync before evaluating this server.']]}}
 const m={tph:peerMedian(rows,'tablesPerHour'),gph:peerMedian(rows,'guestsPerHour'),gap:peerMedian(rows,'medianSeatGap'),sph:peerMedian(rows,'salesPerHour'),spg:peerMedian(rows,'salesPerGuest'),spt:peerMedian(rows,'salesPerTable'),tiph:peerMedian(rows,'tipPerHour'),rph:peerMedian(rows,'rotationPerHour')};
 if(row.paceScore<45){if(row.tablesPerHour<m.tph*.88)causes.push(id?'Meja per jam di bawah kelompok pembanding.':'Tables per hour are below the peer group.');if(row.guestsPerHour<m.gph*.88)causes.push(id?'Tamu per jam di bawah kelompok pembanding.':'Guests per hour are below the peer group.');if(row.medianSeatGap&&m.gap&&row.medianSeatGap>m.gap*1.18)causes.push(id?'Jeda antar seating lebih panjang dari median tim.':'The gap between seating events is longer than the team median.');actions.push(id?'Cek dulu kesempatan floor: section, ketersediaan meja, skip, dan ukuran party. Jika opportunity setara, coaching fokus pada kesiapan meja, alur order, pre-bussing, dan komunikasi dengan host.':'First check floor opportunity: section, table availability, skips, and party mix. If opportunity was comparable, coach table readiness, order flow, pre-bussing, and host communication.')}
 if(row.salesScore<45){if(row.salesPerGuest<m.spg*.9){causes.push(id?'Penjualan per tamu rendah: average check perlu ditingkatkan.':'Sales per guest are low: average check needs improvement.');actions.push(id?'Latih suggestive selling: minuman, appetizer, add-on, combo upgrade, dan dessert tanpa memaksa customer.':'Coach suggestive selling: beverages, appetizers, add-ons, combo upgrades, and dessert without pressuring guests.')}if(row.salesPerHour<m.sph*.88&&row.salesPerGuest>=m.spg*.9){causes.push(id?'Sales per jam rendah walau average check relatif normal; kemungkinan masalah throughput/opportunity, bukan upselling.':'Sales per hour are low while average check is relatively normal; this points more to throughput/opportunity than upselling.');actions.push(id?'Review rotasi, section, dan jumlah meja sebelum memberi coaching penjualan.':'Review rotation, section, and table opportunity before applying sales coaching.')}}
 if(row.tipScore<45){causes.push(id?'Pendapatan tip per jam/tamu di bawah peer group.':'Tip income per hour/guest is below the peer group.');actions.push(id?'Jangan langsung menyimpulkan service buruk. Cek cash-tip entry, party mix, complaint/feedback, dan kualitas service sebelum coaching.':'Do not automatically conclude poor service. Check cash-tip entry, party mix, complaints/feedback, and service quality before coaching.')}
 if(m.rph&&row.rotationPerHour<m.rph*.78){causes.push(id?'Kesempatan rotasi per jam lebih rendah dari median tim.':'Rotation opportunity per hour is below the team median.');actions.push(id?'Audit section assignment dan skip history. Server tidak boleh dihukum karena opportunity floor yang lebih rendah.':'Audit section assignment and skip history. Do not penalize the server for lower floor opportunity.')}
 if(!causes.length)causes.push(id?'Tidak ada kelemahan utama yang terdeteksi dari metrik lengkap pada periode ini.':'No major weakness was detected from the complete metrics in this period.');
 if(!actions.length)actions.push(id?'Pertahankan pola kerja, monitor konsistensi, dan bandingkan lagi pada periode yang lebih panjang.':'Maintain the current pattern, monitor consistency, and compare again over a longer period.');
 const status=row.overall>=70?(id?'KUAT':'STRONG'):row.overall>=45?(id?'PERLU DIPANTAU':'WATCH'):(id?'PRIORITAS COACHING':'COACHING PRIORITY');return {status,causes:[...new Set(causes)],actions:[...new Set(actions)]}
}
function analyze(rows){const complete=rows.filter(x=>x.dataComplete).sort((a,b)=>b.overall-a.overall),strongest=complete[0]||null,weakest=complete.length>1?complete.at(-1):null,fastest=[...complete].sort((a,b)=>b.paceScore-a.paceScore)[0]||null,slowest=complete.length>1?[...complete].sort((a,b)=>a.paceScore-b.paceScore)[0]:null,bestSales=[...complete].sort((a,b)=>b.salesScore-a.salesScore)[0]||null,lowestSales=complete.length>1?[...complete].sort((a,b)=>a.salesScore-b.salesScore)[0]:null,incomplete=rows.filter(x=>x.hasPerformance&&!x.dataComplete),fairness=groupFairness(rows);return {complete,strongest,weakest,fastest,slowest,bestSales,lowestSales,incomplete,fairness}}
function rebuild(){state.rows=buildRows();state.analysis=analyze(state.rows);state.rawNames=[...new Set([...state.board.map(e=>e.rawServer),...state.boardRoster.map(r=>r.rawServer),...state.tipRoster.map(r=>r.rawServer),...state.tips.map(r=>reportName(r)).filter(Boolean)])].filter(Boolean).sort();$('updatedAt').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});renderKpis();renderContent()}

function renderKpis(){const t=totals(state.rows),complete=state.analysis?.complete?.length||0;$('kpis').innerHTML=[['Tables',t.tables,'Board seatings'],['Guests',t.guests,t.tables?n1(t.guests/t.tables)+' avg party':'—'],['Sales',money(t.sales),t.guests?money(t.sales/t.guests)+' / guest':'—'],['Hours',n1(t.hours),complete+' fully rankable'],['Tip Income',money(t.tip),t.hours?money(t.tip/t.hours)+' / hr':'—'],['Rotation Fairness',state.analysis?.fairness==null?'—':Math.round(state.analysis.fairness)+'%',state.analysis?.incomplete?.length?state.analysis.incomplete.length+' incomplete server(s)':'complete data']].map(x=>`<div class="kpi"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}
function scoreCell(x,key){const v=x[key];return v==null?'—':`<span class="score ${scoreClass(v)}">${Math.round(v)}</span>`}
function rowTable(rows=state.rows){let rank=0;return `<div class="tablewrap"><table><thead><tr><th>Server</th><th>Overall</th><th>Pace</th><th>Sales Eff.</th><th>Tip Eff.</th><th>Data</th><th>Hours</th><th>Tables</th><th>Guests</th><th>Rotation</th><th>Sales</th><th>Tip</th><th>Sales/Hr</th><th>Guests/Hr</th><th>Tables/Hr</th><th>Sales/Guest</th><th>Seat Gap</th></tr></thead><tbody>${rows.map(x=>{const rn=x.dataComplete?++rank:'—';return `<tr class="clickrow" data-server="${esc(x.name)}"><td><span class="rank">${rn}</span><b>${esc(x.name)}</b>${x.active?'':' <span class="tag">INACTIVE</span>'}${!x.hasPerformance?' <span class="tag">ROSTER</span>':''}</td><td>${scoreCell(x,'overall')}</td><td>${scoreCell(x,'paceScore')}</td><td>${scoreCell(x,'salesScore')}</td><td>${scoreCell(x,'tipScore')}</td><td><span class="badge ${x.dataComplete?'strong':x.hasPerformance?'warn':'neutral'}">${x.dataComplete?'COMPLETE':x.hasPerformance?'INCOMPLETE':'ROSTER'}</span></td><td>${n1(x.hours)}</td><td>${x.tables}</td><td>${x.guests}</td><td>${x.rotation}</td><td>${money(x.sales)}</td><td>${money(x.tipIncome)}</td><td>${x.hours?money(x.salesPerHour):'—'}</td><td>${x.hours?n1(x.guestsPerHour):'—'}</td><td>${x.hours?n1(x.tablesPerHour):'—'}</td><td>${x.guests?money(x.salesPerGuest):'—'}</td><td>${x.medianSeatGap?n1(x.medianSeatGap)+' min':'—'}</td></tr>`}).join('')}</tbody></table></div>`}
function bars(title,rows,key,format=v=>n1(v),eligibleFn=x=>x.dataComplete){const a=[...rows.filter(eligibleFn)].sort((x,y)=>num(y[key])-num(x[key])).slice(0,8),mx=Math.max(1,...a.map(x=>num(x[key])));return `<div class="card"><div class="section-title"><h2>${title}</h2><small>${a.length?'Top '+a.length:'No complete data'}</small></div>${a.map((x,i)=>`<div class="barrow"><span>${i+1}. ${esc(x.name)}</span><div class="bartrack"><i style="width:${Math.max(3,num(x[key])/mx*100)}%"></i></div><b>${format(x[key])}</b></div>`).join('')||'<p class="muted">Ranking waits for complete Board + Tip data.</p>'}</div>`}
function executiveHTML(){const a=state.analysis,t=totals(state.rows),weak=a.weakest,weakD=weak?diagnose(weak,state.rows,'EN'):null;return `<div class="summaryGrid"><div class="card heroInsight"><span class="badge strong">STRONGEST COMPLETE DATA</span><div class="bigName">${a.strongest?esc(a.strongest.name):'Waiting for complete data'}</div><p>${a.strongest?`Overall ${Math.round(a.strongest.overall)} • Pace ${Math.round(a.strongest.paceScore)} • Sales efficiency ${Math.round(a.strongest.salesScore)} • Tip efficiency ${Math.round(a.strongest.tipScore)}`:'Server ranking will appear only when both Board activity and final Tip/hours data are available.'}</p><div class="dimensionGrid" style="margin-top:16px"><div class="dim"><span>Fastest Pace</span><b>${a.fastest?esc(a.fastest.name):'—'}</b><small>${a.fastest?Math.round(a.fastest.paceScore)+'/100':'—'}</small></div><div class="dim"><span>Best Sales Efficiency</span><b>${a.bestSales?esc(a.bestSales.name):'—'}</b><small>${a.bestSales?Math.round(a.bestSales.salesScore)+'/100':'—'}</small></div><div class="dim"><span>Rotation Fairness</span><b>${a.fairness==null?'—':Math.round(a.fairness)+'%'}</b><small>guest share vs rotation load</small></div><div class="dim"><span>Data Complete</span><b>${a.complete.length}</b><small>${a.incomplete.length} incomplete</small></div></div></div><div class="card heroInsight"><span class="badge weak">WEAKEST / COACHING FOCUS</span><div class="bigName">${weak?esc(weak.name):'Not enough ranked servers'}</div>${weak?`<p><b>Overall ${Math.round(weak.overall)}/100</b> • Pace ${Math.round(weak.paceScore)} • Sales ${Math.round(weak.salesScore)} • Tip ${Math.round(weak.tipScore)}</p><div class="insightList">${weakD.causes.slice(0,3).map(x=>`<div class="insight"><b>Why</b><span>${esc(x)}</span></div>`).join('')}</div><div class="recommend" style="margin-top:11px"><b>Recommended action:</b> ${esc(weakD.actions[0])}</div>`:`<p>At least two servers need complete Board + Tip data before the app identifies a weakest server.</p>`}</div></div><div class="grid2" style="margin-top:14px">${bars('Overall Performance Index',state.rows,'overall',v=>Math.round(v))}${bars('Pace Score',state.rows,'paceScore',v=>Math.round(v))}</div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Server Summary</h2><small>${state.from} → ${state.to}</small></div>${rowTable()}</div><div class="recommend" style="margin-top:14px"><b>How V1.2 judges performance:</b> Overall = 40% Pace + 40% Sales Efficiency + 20% Tip Efficiency. Rotation is context, not a punishment. A server is not scored when Board + final Tip/hours data are incomplete.</div>`}
function renderContent(){const c=$('content'),r=state.rows;if(state.tab==='overview')c.innerHTML=executiveHTML();else if(state.tab==='ranking')c.innerHTML=`<div class="grid2">${bars('Overall Performance',r,'overall',v=>Math.round(v))}${bars('Fastest Pace',r,'paceScore',v=>Math.round(v))}${bars('Sales Efficiency',r,'salesScore',v=>Math.round(v))}${bars('Tip Efficiency',r,'tipScore',v=>Math.round(v))}</div><div class="card" style="margin-top:14px">${rowTable()}</div>`;else if(state.tab==='rotation')c.innerHTML=rotationHTML();else if(state.tab==='finance')c.innerHTML=`<div class="grid2">${bars('Sales / Hour',r,'salesPerHour',money)}${bars('Sales / Guest',r,'salesPerGuest',money)}${bars('Tip / Hour',r,'tipPerHour',money)}${bars('Guests / Hour',r,'guestsPerHour',n1)}</div><div class="card" style="margin-top:14px">${rowTable([...r].sort((a,b)=>b.salesPerHour-a.salesPerHour))}</div>`;else renderTables(c);bindRows()}
function rotationHTML(){const a=state.analysis;return `<div class="summaryGrid"><div class="card heroInsight"><span class="badge info">ROTATION CONTEXT</span><div class="bigName">${a.fairness==null?'—':Math.round(a.fairness)+'% fairness'}</div><p>Fairness compares each server's share of rotation load with their share of guests. It is context for management, not a server performance grade.</p></div><div class="card heroInsight"><span class="badge ${a.slowest?'warn':'neutral'}">PACE WATCH</span><div class="bigName">${a.slowest?esc(a.slowest.name):'Waiting for data'}</div><p>${a.slowest?`Lowest complete pace score: ${Math.round(a.slowest.paceScore)}/100. Review floor opportunity before coaching.`:'At least two complete servers are needed.'}</p></div></div><div class="grid2" style="margin-top:14px">${bars('Rotation Load / Hour',state.rows,'rotationPerHour',n1)}${bars('Guests / Rotation Load',state.rows,'guestsPerRotation',n1,x=>x.hasBoardActivity)}</div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Rotation & Pace Detail</h2><small>Seat gap measures interval between seating events, not table-service duration.</small></div>${rowTable([...state.rows].sort((a,b)=>num(b.rotationPerHour)-num(a.rotationPerHour)))}</div>`}
function renderTables(c){const map=new Map();state.board.forEach(e=>{if(!map.has(e.table))map.set(e.table,{table:e.table,seatings:0,guests:0,servers:new Map()});const x=map.get(e.table);x.seatings++;x.guests+=e.people;x.servers.set(e.server,(x.servers.get(e.server)||0)+1)});const a=[...map.values()].sort((x,y)=>y.seatings-x.seatings);c.innerHTML=`<div class="card"><div class="section-title"><h2>Table Utilization</h2><small>Selected period</small></div><div class="tablewrap"><table><thead><tr><th>Table</th><th>Seatings</th><th>Guests</th><th>Avg Party</th><th>Most Frequent Server</th></tr></thead><tbody>${a.map(x=>{const top=[...x.servers].sort((p,q)=>q[1]-p[1])[0];return `<tr><td><b>${esc(x.table)}</b></td><td>${x.seatings}</td><td>${x.guests}</td><td>${n1(x.guests/x.seatings)}</td><td>${top?esc(top[0])+' ('+top[1]+')':'—'}</td></tr>`}).join('')}</tbody></table></div></div>`}
function bindRows(){document.querySelectorAll('[data-server]').forEach(tr=>tr.onclick=()=>openServer(tr.dataset.server))}
function openServer(name){const x=state.rows.find(r=>r.name===name);if(!x)return;const d=diagnose(x,state.rows,'EN'),events=[...x.events].sort((a,b)=>(a.date+a.shift).localeCompare(b.date+b.shift)||a.seatedAt-b.seatedAt);$('modalTitle').textContent=name+' • Performance Diagnosis';$('modalBody').innerHTML=`<div class="dimensionGrid"><div class="dim"><span>Overall</span><b>${x.overall==null?'N/A':Math.round(x.overall)}</b><small>${d.status}</small></div><div class="dim"><span>Pace</span><b>${x.paceScore==null?'—':Math.round(x.paceScore)}</b><small>${n1(x.tablesPerHour)} tables/hr</small></div><div class="dim"><span>Sales Efficiency</span><b>${x.salesScore==null?'—':Math.round(x.salesScore)}</b><small>${money(x.salesPerHour)}/hr</small></div><div class="dim"><span>Tip Efficiency</span><b>${x.tipScore==null?'—':Math.round(x.tipScore)}</b><small>${money(x.tipPerHour)}/hr</small></div></div><div class="summaryGrid" style="margin-top:14px"><div class="card"><h2>Root Cause Analysis</h2><div class="insightList">${d.causes.map((v,i)=>`<div class="insight"><b>${i+1}. Finding</b><span>${esc(v)}</span></div>`).join('')}</div></div><div class="card"><h2>Management Solutions</h2><div class="insightList">${d.actions.map((v,i)=>`<div class="insight"><b>${i+1}. Action</b><span>${esc(v)}</span></div>`).join('')}</div></div></div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Work & Financial Detail</h2><small>${[...x.aliases].map(esc).join(' • ')||esc(x.name)}</small></div><div class="dimensionGrid"><div class="dim"><span>Tables / Guests</span><b>${x.tables} / ${x.guests}</b><small>${n1(x.avgParty)} avg party</small></div><div class="dim"><span>Rotation</span><b>${x.rotation}</b><small>${n1(x.rotationPerHour)} / hr</small></div><div class="dim"><span>Sales</span><b>${money(x.sales)}</b><small>${money(x.salesPerGuest)} / guest</small></div><div class="dim"><span>Tip Income</span><b>${money(x.tipIncome)}</b><small>${money(x.tipPerGuest)} / guest</small></div></div></div><div class="card" style="margin-top:14px"><h2>Seating History</h2><div class="tablewrap" style="margin-top:10px"><table><thead><tr><th>Date</th><th>Shift</th><th>Time</th><th>Table</th><th>Guests</th><th>Section</th><th>Rotation Load</th><th>Source</th></tr></thead><tbody>${events.map(e=>`<tr><td>${e.date}</td><td>${e.shift}</td><td>${e.seatedAt?new Date(e.seatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'}</td><td>${esc(e.table)}</td><td>${e.people}</td><td>${esc(e.section)}</td><td>${e.rotationSlots}</td><td>${e.source}</td></tr>`).join('')}</tbody></table></div></div>`;$('modal').classList.remove('hidden')}

function identityModal(){const groups=new Map();state.rawNames.forEach(n=>{const c=canonical(n);if(!groups.has(c))groups.set(c,[]);groups.get(c).push(n)});$('modalTitle').textContent='Employee Identity Sync';$('modalBody').innerHTML=`<p class="muted">Merge different Board/Tip names into one analytics identity. Source apps are never rewritten.</p><div class="aliasgrid">${[...groups].sort().map(([c,aliases])=>`<div class="aliasitem"><div><b>${esc(c)}</b><div class="muted">${aliases.map(esc).join(' • ')}</div></div><span class="tag">${isActiveName(c)?'ACTIVE':'INACTIVE'}</span></div>`).join('')}</div><div class="card" style="margin-top:14px"><h2>Merge / Rename</h2><div class="grid2" style="margin-top:12px"><div class="field"><label>Source name / alias</label><select id="aliasSource">${state.rawNames.map(n=>`<option>${esc(n)}</option>`).join('')}</select></div><div class="field"><label>Canonical employee name</label><input id="aliasCanonical" placeholder="Example: Ariana Garner"></div></div><div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap"><button class="btn primary" id="mergeAlias">Save Alias</button><button class="btn" id="toggleInactive">Toggle Active / Inactive</button><button class="btn red" id="resetAliases">Reset Defaults</button></div></div>`;$('modal').classList.remove('hidden');$('mergeAlias').onclick=()=>{const s=$('aliasSource').value,c=normName($('aliasCanonical').value);if(!s||!c)return alert('Choose source name and canonical name.');identity[idKey(s)]={canonical:c,active:identity[idKey(s)]?.active!==false};identity[idKey(c)]={canonical:c,active:identity[idKey(c)]?.active!==false};saveIdentity();refreshBoard();identityModal()};$('toggleInactive').onclick=()=>{const s=$('aliasSource').value,c=canonical(s),active=isActiveName(c);Object.keys(identity).forEach(k=>{if(identity[k].canonical===c)identity[k].active=!active});identity[idKey(c)]={canonical:c,active:!active};saveIdentity();rebuild();identityModal()};$('resetAliases').onclick=()=>{if(confirm('Reset identity aliases to app defaults?')){localStorage.removeItem('fzsi_identity_v12');localStorage.removeItem('fzsi_identity_v11');localStorage.removeItem('fzsi_identity_v1');identity=loadIdentity();saveIdentity();rebuild();identityModal()}}}

/* ---------- 3-page bilingual executive PDF ---------- */
const PDF_LANG={EN:{report:'SERVER PERFORMANCE INTELLIGENCE',exec:'EXECUTIVE SUMMARY',comparison:'SERVER COMPARISON & COACHING',rotation:'ROTATION, FAIRNESS & ACTION PLAN',period:'Period',strongest:'Strongest Complete Server',weakest:'Weakest / Coaching Priority',fastest:'Fastest Pace',sales:'Best Sales Efficiency',fairness:'Rotation Fairness',complete:'Rankable Servers',key:'Key Conclusions',why:'Why this server is weak',actions:'Recommended Management Actions',data:'Data Quality',noWeak:'Not enough complete servers to identify a weakest server.',method:'Overall Index = 40% Pace + 40% Sales Efficiency + 20% Tip Efficiency. It is peer-relative within the selected period. Rotation is management context, not a punishment. Pace is seating throughput, not service-completion time.',incomplete:'Incomplete data is excluded from performance ranking.'},ID:{report:'INTELIJEN KINERJA SERVER',exec:'RINGKASAN EKSEKUTIF',comparison:'PERBANDINGAN SERVER & COACHING',rotation:'ROTASI, KEADILAN & RENCANA TINDAKAN',period:'Periode',strongest:'Server Terkuat (Data Lengkap)',weakest:'Server Terlemah / Prioritas Coaching',fastest:'Pace Tercepat',sales:'Efisiensi Sales Terbaik',fairness:'Keadilan Rotasi',complete:'Server Bisa Diranking',key:'Kesimpulan Utama',why:'Mengapa server ini lemah',actions:'Solusi Manajemen yang Disarankan',data:'Kualitas Data',noWeak:'Belum cukup server dengan data lengkap untuk menentukan server terlemah.',method:'Overall Index = 40% Pace + 40% Efisiensi Sales + 20% Efisiensi Tip. Nilai bersifat relatif terhadap peer pada periode terpilih. Rotasi adalah konteks manajemen, bukan hukuman. Pace adalah throughput seating, bukan waktu penyelesaian service.',incomplete:'Data yang belum lengkap tidak dimasukkan ke ranking performa.'}};
function pdfText(d,text,x,y,maxW,fontSize=9,color=[45,68,88],style='normal'){d.setFont('helvetica',style);d.setFontSize(fontSize);d.setTextColor(...color);const lines=d.splitTextToSize(txt(text),maxW);d.text(lines,x,y);return y+lines.length*(fontSize*1.18)}
function pdfCard(d,x,y,w,h,title,value,sub,color=[28,194,220]){d.setFillColor(205,225,238);d.roundedRect(x+5,y+7,w,h,14,14,'F');d.setFillColor(255,255,255);d.setDrawColor(205,226,238);d.roundedRect(x,y,w,h,14,14,'FD');d.setFillColor(...color);d.roundedRect(x,y,6,h,4,4,'F');pdfText(d,title,x+15,y+19,w-25,7,[93,118,138],'bold');pdfText(d,value,x+15,y+42,w-25,18,[20,49,72],'bold');if(sub)pdfText(d,sub,x+15,y+h-12,w-25,6.8,[104,126,143],'normal')}
function pdfHeader(d,L,pageTitle,page){d.setFillColor(246,252,255);d.rect(0,0,792,612,'F');d.setFillColor(21,199,223);d.roundedRect(0,0,792,9,0,0,'F');d.setFillColor(62,124,244);d.roundedRect(210,0,350,9,0,0,'F');d.setFillColor(139,99,246);d.roundedRect(520,0,272,9,0,0,'F');pdfText(d,'FZ SERVER INTELLIGENCE V1.2',30,38,350,15,[19,55,83],'bold');pdfText(d,pageTitle,30,60,520,11,[74,91,112],'bold');pdfText(d,`${L.period}: ${state.from} → ${state.to} • ${state.shift}`,30,78,500,8,[108,128,145]);pdfText(d,`Page ${page}/3`,710,38,55,8,[108,128,145],'bold')}
function draw3DBarChart(d,x,y,w,h,items,title,valueFn=v=>Math.round(v)){pdfText(d,title,x,y+12,w,9,[35,66,93],'bold');const data=items.slice(0,6),max=Math.max(1,...data.map(a=>num(a.value))),barY=y+28,rowH=(h-35)/Math.max(1,data.length);data.forEach((it,i)=>{const yy=barY+i*rowH,bw=(w-145)*num(it.value)/max;pdfText(d,(i+1)+'. '+it.name,x,yy+9,125,7.2,[55,78,98],'bold');d.setFillColor(219,231,240);d.roundedRect(x+130,yy+3,w-170,11,5,5,'F');d.setFillColor(150,111,235);d.roundedRect(x+133,yy+6,bw,11,5,5,'F');d.setFillColor(42,194,223);d.roundedRect(x+130,yy+3,bw,10,5,5,'F');d.setFillColor(255,255,255);if(bw>24)d.roundedRect(x+134,yy+5,Math.min(24,bw-5),2,1,1,'F');pdfText(d,valueFn(it.value),x+w-35,yy+11,32,7,[31,62,86],'bold')})}
function pdfBulletList(d,items,x,y,w,{font=8,color=[55,77,96],bullet=[59,124,244],limit=5}={}){let yy=y;for(const item of items.slice(0,limit)){d.setFillColor(...bullet);d.circle(x+4,yy-2,2.2,'F');yy=pdfText(d,item,x+12,yy,w-12,font,color,'normal')+5}return yy}
function pdfReport(lang='EN'){
 const J=window.jspdf?.jsPDF;if(!J)return alert('PDF library unavailable.');const L=PDF_LANG[lang],id=lang==='ID',d=new J({orientation:'landscape',unit:'pt',format:'letter'}),a=state.analysis,t=totals(state.rows),ranked=a.complete,weak=a.weakest,weakD=weak?diagnose(weak,state.rows,lang):null;
 // PAGE 1
 pdfHeader(d,L,L.exec,1);pdfCard(d,30,98,115,72,id?'Meja':'Tables',String(t.tables),id?'Total seating':'Total seatings',[23,199,225]);pdfCard(d,154,98,115,72,id?'Tamu':'Guests',String(t.guests),t.tables?n1(t.guests/t.tables)+(id?' rata-rata party':' avg party'):'—',[63,125,244]);pdfCard(d,278,98,115,72,id?'Penjualan':'Sales',money(t.sales),t.guests?money(t.sales/t.guests)+(id?' / tamu':' / guest'):'—',[139,99,246]);pdfCard(d,402,98,115,72,id?'Pendapatan Tip':'Tip Income',money(t.tip),t.hours?money(t.tip/t.hours)+(id?' / jam':' / hr'):'—',[239,93,184]);pdfCard(d,526,98,115,72,L.fairness,a.fairness==null?'—':Math.round(a.fairness)+'%',id?'Share guest vs beban rotasi':'Guest share vs rotation load',[57,189,130]);pdfCard(d,650,98,112,72,L.complete,String(ranked.length),a.incomplete.length+(id?' data belum lengkap':' incomplete'),[244,180,60]);
 pdfCard(d,30,187,232,92,L.strongest,a.strongest?a.strongest.name:'—',a.strongest?`Overall ${Math.round(a.strongest.overall)} • Pace ${Math.round(a.strongest.paceScore)} • Sales ${Math.round(a.strongest.salesScore)}`:'Waiting for complete data',[57,189,130]);pdfCard(d,272,187,232,92,L.weakest,weak?weak.name:'—',weak?`Overall ${Math.round(weak.overall)} • Pace ${Math.round(weak.paceScore)} • Sales ${Math.round(weak.salesScore)}`:L.noWeak,[235,95,115]);pdfCard(d,514,187,248,92,L.fastest,a.fastest?a.fastest.name:'—',a.fastest?`${Math.round(a.fastest.paceScore)}/100 • ${n1(a.fastest.tablesPerHour)} tables/hr • ${n1(a.fastest.guestsPerHour)} guests/hr`:'—',[28,194,220]);
 draw3DBarChart(d,30,300,360,190,ranked.map(x=>({name:x.name,value:x.overall})),'5D • Overall Performance',v=>Math.round(v));draw3DBarChart(d,410,300,352,190,ranked.map(x=>({name:x.name,value:x.paceScore})),id?'5D • Pace / Kecepatan':'5D • Pace / Throughput',v=>Math.round(v));
 pdfText(d,L.key,30,512,210,10,[30,57,81],'bold');const conclusions=[];if(a.strongest)conclusions.push(id?`${a.strongest.name} adalah performa gabungan terkuat dari server dengan data lengkap.`:`${a.strongest.name} has the strongest combined performance among servers with complete data.`);if(weak)conclusions.push(id?`${weak.name} menjadi prioritas coaching; penyebab utama harus dibaca bersama konteks rotasi.`:`${weak.name} is the coaching priority; root causes must be read together with rotation context.`);if(a.fairness!=null)conclusions.push(id?`Keadilan rotasi periode ini ${Math.round(a.fairness)}%. Semakin dekat 100%, semakin selaras beban rotasi dengan distribusi tamu.`:`Rotation fairness is ${Math.round(a.fairness)}%. Closer to 100% means rotation load is more aligned with guest distribution.`);if(a.incomplete.length)conclusions.push(id?`${a.incomplete.length} server memiliki data belum lengkap dan dikeluarkan dari ranking agar tidak menghasilkan kesimpulan palsu.`:`${a.incomplete.length} server(s) have incomplete data and are excluded from ranking to avoid false conclusions.`);pdfBulletList(d,conclusions,30,530,732,{font:7.7,limit:4});
 // PAGE 2
 d.addPage();pdfHeader(d,L,L.comparison,2);const head=id?['#','Server','Overall','Pace','Sales','Tip','Jam','Meja','Tamu','Sales','Sales/Jam','Tamu/Jam','Rotasi/Jam']:['#','Server','Overall','Pace','Sales','Tip','Hours','Tables','Guests','Sales','Sales/Hr','Guests/Hr','Rotation/Hr'];const body=ranked.slice(0,12).map((x,i)=>[i+1,x.name,Math.round(x.overall),Math.round(x.paceScore),Math.round(x.salesScore),Math.round(x.tipScore),n1(x.hours),x.tables,x.guests,money(x.sales),money(x.salesPerHour),n1(x.guestsPerHour),n1(x.rotationPerHour)]);d.autoTable({startY:98,head:[head],body,theme:'grid',margin:{left:30,right:30},styles:{fontSize:7.1,cellPadding:4,textColor:[35,60,80],lineColor:[216,232,241]},headStyles:{fillColor:[50,125,244],textColor:255,fontStyle:'bold'},alternateRowStyles:{fillColor:[246,251,255]},columnStyles:{1:{cellWidth:100}}});let y=Math.max(285,d.lastAutoTable.finalY+18);pdfText(d,L.weakest,30,y,350,11,[158,51,68],'bold');if(weak){y=pdfText(d,`${weak.name} • Overall ${Math.round(weak.overall)}/100 • Pace ${Math.round(weak.paceScore)} • Sales ${Math.round(weak.salesScore)} • Tip ${Math.round(weak.tipScore)}`,30,y+18,350,8.5,[45,70,90],'bold')+8;pdfText(d,L.why,30,y,330,8.5,[50,74,94],'bold');y=pdfBulletList(d,weakD.causes,30,y+15,330,{font:7.6,bullet:[235,95,115],limit:4})+5;pdfText(d,L.actions,410,Math.max(305,d.lastAutoTable.finalY+18),330,8.5,[50,74,94],'bold');pdfBulletList(d,weakD.actions,410,Math.max(323,d.lastAutoTable.finalY+36),330,{font:7.6,bullet:[57,189,130],limit:4})}else pdfText(d,L.noWeak,30,y+22,700,9,[90,106,121]);
 draw3DBarChart(d,410,440,332,130,ranked.map(x=>({name:x.name,value:x.salesScore})),id?'5D • Efisiensi Sales':'5D • Sales Efficiency',v=>Math.round(v));pdfText(d,L.incomplete,30,579,720,6.8,[107,124,139]);
 // PAGE 3
 d.addPage();pdfHeader(d,L,L.rotation,3);pdfCard(d,30,98,170,72,L.fairness,a.fairness==null?'—':Math.round(a.fairness)+'%',id?'Distribusi tamu vs beban rotasi':'Guest distribution vs rotation load',[57,189,130]);pdfCard(d,210,98,170,72,id?'Pace Terendah':'Lowest Pace',a.slowest?a.slowest.name:'—',a.slowest?Math.round(a.slowest.paceScore)+'/100':'—',[244,180,60]);pdfCard(d,390,98,170,72,id?'Sales Efisiensi Terendah':'Lowest Sales Efficiency',a.lowestSales?a.lowestSales.name:'—',a.lowestSales?Math.round(a.lowestSales.salesScore)+'/100':'—',[235,95,115]);pdfCard(d,570,98,192,72,L.data,a.incomplete.length+(id?' belum lengkap':' incomplete'),id?'Tidak ikut ranking':'Excluded from ranking',[63,125,244]);
 draw3DBarChart(d,30,195,350,180,state.rows.filter(x=>x.hasBoardActivity).map(x=>({name:x.name,value:x.rotationPerHour})),id?'5D • Beban Rotasi / Jam':'5D • Rotation Load / Hour',v=>n1(v));draw3DBarChart(d,410,195,352,180,ranked.map(x=>({name:x.name,value:x.salesPerHour})),id?'5D • Sales / Jam':'5D • Sales / Hour',v=>money(v));
 pdfText(d,id?'RENCANA TINDAKAN OWNER':'OWNER ACTION PLAN',30,405,300,10,[32,61,84],'bold');const plan=[];if(weak&&weakD)plan.push(...weakD.actions.slice(0,2));if(a.fairness!=null&&a.fairness<80)plan.push(id?'Audit section, skip, dan pembagian rotation sebelum menggunakan ranking untuk coaching.':'Audit section, skips, and rotation allocation before using ranking for coaching.');if(a.incomplete.length)plan.push(id?'Finalisasi data Tip/jam untuk server yang incomplete sebelum membuat keputusan disipliner atau evaluasi final.':'Finalize Tip/hours data for incomplete servers before any disciplinary or final evaluation decision.');if(!plan.length)plan.push(id?'Tidak ada tindakan kritis; lanjutkan monitoring konsistensi mingguan dan bulanan.':'No critical action detected; continue weekly and monthly consistency monitoring.');pdfBulletList(d,plan,30,425,350,{font:8,bullet:[139,99,246],limit:5});pdfText(d,id?'CATATAN METODOLOGI':'METHODOLOGY NOTES',410,405,330,10,[32,61,84],'bold');let my=425;my=pdfText(d,L.method,410,my,335,7.5,[73,94,110])+8;my=pdfText(d,id?'Solusi yang diberikan adalah rekomendasi manajemen berbasis data, bukan kesimpulan otomatis tentang kualitas pribadi server. Selalu cek kondisi floor, section, party mix, dan kelengkapan data.':'Recommendations are data-informed management actions, not automatic conclusions about a server’s personal quality. Always check floor conditions, section, party mix, and data completeness.',410,my,335,7.5,[73,94,110])+8;pdfText(d,L.incomplete,410,my,335,7.5,[107,124,139],'bold');
 d.save(`FZ_Server_Intelligence_V1.2_${lang}_${state.from}_${state.to}.pdf`)
}
function pdfMenu(){$('modalTitle').textContent='3-Page Executive PDF';$('modalBody').innerHTML=`<div class="grid2"><button class="btn primary" id="pdfEN" style="padding:30px;font-size:18px">English • 3 Pages</button><button class="btn gold" id="pdfID" style="padding:30px;font-size:18px">Bahasa Indonesia • 3 Halaman</button></div><div class="recommend" style="margin-top:14px"><b>Included:</b> Executive summary, 5D diagrams, strongest/weakest server, root-cause analysis, specific management solutions, server comparison, rotation fairness, and action plan.</div>`;$('modal').classList.remove('hidden');$('pdfEN').onclick=()=>pdfReport('EN');$('pdfID').onclick=()=>pdfReport('ID')}

async function ownerLogin(){const u=$('user').value.trim(),p=$('pass').value;if(!u||!p){$('loginMsg').textContent='Enter Owner username/email and password.';return}const btn=$('loginBtn');try{btn.disabled=true;$('loginMsg').textContent='Signing in…';await authReady;await setPersistence(auth,browserSessionPersistence);await signInWithEmailAndPassword(auth,emailFor(u),p)}catch(e){console.error('Owner login:',e);$('loginMsg').textContent='Login failed: '+(e.code||e.message||'unknown error')}finally{btn.disabled=false}}
$('loginBtn').onclick=ownerLogin;
$('pass').addEventListener('keydown',e=>{if(e.key==='Enter')ownerLogin()});
onAuthStateChanged(auth,async user=>{try{if(!user){profile=null;$('loginView').classList.remove('hidden');$('app').classList.add('hidden');return} $('loginMsg').textContent='Verifying Owner account…';const s=await getDoc(doc(db,'users',user.uid));const p=s.exists()?s.data():null;const role=txt(p?.role).trim().toLowerCase();if(!p||p.active===false||role!=='owner'){await signOut(auth);$('loginMsg').textContent='Owner account required. Role found: '+(role||'none');return}profile=p;$('ownerName').textContent=p.displayName||p.username||'OWNER';$('loginMsg').textContent='';$('loginView').classList.add('hidden');$('app').classList.remove('hidden');setMode('daily');if(timer)clearInterval(timer);timer=setInterval(refreshBoard,30000)}catch(e){console.error('Owner verification:',e);try{await signOut(auth)}catch(_){}$('loginView').classList.remove('hidden');$('app').classList.add('hidden');$('loginMsg').textContent='Owner verification failed: '+(e.code||e.message||'unknown error')}});
$('logoutBtn').onclick=()=>signOut(auth);$('refreshBtn').onclick=()=>{state.from=$('from').value;state.to=$('to').value;state.shift=$('shift').value;subscribeTips();refreshBoard()};$('aliasBtn').onclick=identityModal;$('pdfBtn').onclick=pdfMenu;$('modalClose').onclick=()=>$('modal').classList.add('hidden');$('modal').addEventListener('click',e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x===b));renderContent()});$('shift').onchange=()=>{state.shift=$('shift').value};
let deferredInstallPrompt=null;const installButtons=[$('installBtn'),$('loginInstallBtn')].filter(Boolean);function refreshInstallButtons(){installButtons.forEach(b=>b.classList.toggle('hidden',!deferredInstallPrompt))}window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;refreshInstallButtons()});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;refreshInstallButtons()});installButtons.forEach(b=>b.onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice}catch(e){}deferredInstallPrompt=null;refreshInstallButtons()});
$('resetCacheBtn')?.addEventListener('click',async()=>{try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('fz-server-intelligence')).map(k=>caches.delete(k)))}$('loginMsg').textContent='App cache cleared. Reloading…';setTimeout(()=>location.reload(true),350)}catch(e){$('loginMsg').textContent='Cache reset failed: '+(e.message||e)}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=121',{updateViaCache:'none'}).then(r=>r.update()).catch(e=>console.warn('SW:',e)));
