import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged,setPersistence,browserSessionPersistence} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import {getFirestore,doc,getDoc,collection,query,where,onSnapshot} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const TIP_CONFIG={apiKey:'AIzaSyB7yIl1T6ufniDAhed1vGNzi8c1d-ghfFI',authDomain:'juicy-tip-all-in-one.firebaseapp.com',projectId:'juicy-tip-all-in-one',storageBucket:'juicy-tip-all-in-one.firebasestorage.app',messagingSenderId:'1018030638724',appId:'1:1018030638724:web:19b945d908229f622664d1'};
const BOARD_ROOT='https://table-live-by-iwanto-zhang-default-rtdb.firebaseio.com/juicyTableLive/JUICY-HUNTSVILLE/flexibleFloorV1';
const app=initializeApp(TIP_CONFIG),auth=getAuth(app),db=getFirestore(app);setPersistence(auth,browserSessionPersistence).catch(()=>{});
const $=id=>document.getElementById(id), num=v=>Number(v)||0, txt=v=>String(v??''), money=v=>'$'+num(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}), n1=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:1});
const esc=s=>txt(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const iso=d=>{const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`};
const today=()=>iso(new Date());
const slug=s=>txt(s).trim().toLowerCase().replace(/[^a-z0-9._-]/g,'');
const emailFor=u=>`${slug(u)}@juicytip.app`;
let profile=null, tipUnsubs=[], timer=null, tipFeed={reports:false,batches:false,error:false}, state={mode:'daily',tab:'overview',from:today(),to:today(),shift:'ALL',board:[],boardRoster:[],tips:[],batches:[],tipRoster:[],rows:[],rawNames:[]};
const DEFAULT_ID={
 'a.j.':{canonical:'Ariana Garner',active:true},'a.j':{canonical:'Ariana Garner',active:true},'aj':{canonical:'Ariana Garner',active:true},
 'ariana garner':{canonical:'Ariana Garner',active:true},'ariana graner':{canonical:'Ariana Garner',active:true},
 'alaina montalvo':{canonical:'Alainna Montalvo',active:true},'alainna montalvo':{canonical:'Alainna Montalvo',active:true},'alainna':{canonical:'Alainna Montalvo',active:true},
 'aida':{canonical:'Aida Gonzales',active:false},'aida gonzales':{canonical:'Aida Gonzales',active:false}
};
function loadIdentity(){
  let stored={};
  try{stored=JSON.parse(localStorage.getItem('fzsi_identity_v11')||localStorage.getItem('fzsi_identity_v1')||'{}')||{}}catch(e){}
  const merged={...DEFAULT_ID,...stored};
  /* V1.1 repair: force the known A.J. / Ariana identity onto one full-name profile,
     even if a V1 browser saved the old A.J. canonical mapping. */
  for(const k of ['a.j.','a.j','aj','ariana garner','ariana graner'])merged[k]={canonical:'Ariana Garner',active:true};
  return merged;
}
let identity=loadIdentity();
const normName=s=>txt(s).trim().replace(/\s+/g,' ');
function idKey(s){return normName(s).toLowerCase()}
function canonical(s){const n=normName(s);return identity[idKey(n)]?.canonical||n||'Unknown'}
function isActiveName(s){const x=identity[idKey(s)]||identity[idKey(canonical(s))];return x?.active!==false}
function saveIdentity(){localStorage.setItem('fzsi_identity_v11',JSON.stringify(identity));}

function dateList(a,b){const out=[],d=new Date(a+'T12:00:00'),end=new Date(b+'T12:00:00');while(d<=end){out.push(iso(d));d.setDate(d.getDate()+1)}return out}
function setMode(mode){state.mode=mode;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode));const d=new Date();if(mode==='daily'){state.from=state.to=today()}if(mode==='weekly'){const x=new Date();const day=x.getDay()||7;x.setDate(x.getDate()-day+1);state.from=iso(x);x.setDate(x.getDate()+6);state.to=iso(x)}if(mode==='monthly'){state.from=iso(new Date(d.getFullYear(),d.getMonth(),1));state.to=iso(new Date(d.getFullYear(),d.getMonth()+1,0))}syncInputs();subscribeTips();refreshBoard()}
function syncInputs(){$('from').value=state.from;$('to').value=state.to;$('shift').value=state.shift}

async function fetchJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('Board HTTP '+r.status);return r.json()}
function turnArray(x,len=60){if(Array.isArray(x))return x;const a=Array(len).fill(null);Object.entries(x||{}).forEach(([k,v])=>{if(/^\d+$/.test(k))a[+k]=v});return a}
function rowsArray(x){if(Array.isArray(x))return x;const a=Array(15).fill(null);Object.entries(x||{}).forEach(([k,v])=>{if(/^\d+$/.test(k))a[+k]=v});return a}
function epoch(entryId){const m=txt(entryId).match(/^seat_(\d{13})_/);return m?+m[1]:0}
function boardEvents(raw,date,shift){const ev=[];rowsArray(raw?.rows).forEach((r,ri)=>{if(!r)return;turnArray(r.turns).forEach((t,ti)=>{if(!t||t.skipped||!t.table)return;const p=Math.max(0,parseInt(t.people)||0),ts=epoch(t.entryId||t.partyId);ev.push({source:'LIVE',date,shift,server:canonical(r.server||'Unknown'),rawServer:normName(r.server||'Unknown'),section:txt(r.section),table:txt(t.table),people:p,rotationSlots:Math.max(1,Math.ceil(Math.max(1,p)/4)),seatedAt:ts,row:ri,turn:ti})})});return ev}
function archiveEvents(snap){const arr=Array.isArray(snap?.events)?snap.events:Object.values(snap?.events||{});return arr.filter(Boolean).map(e=>({...e,source:'ARCHIVE',server:canonical(e.server),rawServer:normName(e.server),people:num(e.people),rotationSlots:Math.max(1,num(e.rotationSlots)||Math.ceil(Math.max(1,num(e.people))/4))}))}
function boardRosterFromBoard(raw,date,shift){
  const out=[];
  rowsArray(raw?.rows).forEach((r,ri)=>{if(!r||!normName(r.server))return;out.push({date,shift,server:canonical(r.server),rawServer:normName(r.server),section:txt(r.section),workShift:txt(r.workShift||shift),active:r.active!==false,row:ri,source:'BOARD ROSTER'})});
  return out;
}
function teamShiftPeriods(v){const s=txt(v).toUpperCase();if(s.includes('DOUBLE'))return ['AM','PM'];if(s==='AM'||s.includes('10:45')&&s.includes('2'))return ['AM'];if(s==='PM'||s.includes('LONG')||s.includes('2 PM')||s.includes('2–4')||s.includes('2-4'))return ['PM'];return ['AM','PM']}
function boardTeamRoster(raw,date){
  const arr=Array.isArray(raw)?raw:Object.values(raw&&typeof raw==='object'?raw:{}),out=[];
  arr.filter(Boolean).forEach((m,i)=>{const name=normName(m.name||m.server||m.employee);if(!name)return;const role=txt(m.position||m.role||'Server');if(role&&!/server/i.test(role))return;for(const sh of teamShiftPeriods(m.shift||m.workShift)){if(state.shift!=='ALL'&&state.shift!==sh)continue;out.push({date,shift:sh,server:canonical(name),rawServer:name,section:'',workShift:txt(m.shift||sh),active:true,row:i,source:'BOARD TEAM'})}});
  return out;
}
function dedupeRoster(items){const seen=new Set(),out=[];for(const x of items){const k=[x.date,x.shift,idKey(x.server),x.source].join('|');if(seen.has(k))continue;seen.add(k);out.push(x)}return out}
function reportName(r){return normName(r?.employee||r?.employeeDisplayName||r?.name||r?.personName)}
function reportPosition(r){return txt(r?.position||r?.role||r?.employeeSheetRow?.role||r?.employeeSheetRow?.position)}
function batchMemberRole(batch,name,member){const d=batch?.drafts?.[name]||{};return txt(member?.position||member?.role||d?.position||d?.role||d?.employeeSheetRawRow?.role||d?.employeeSheetRawRow?.position||d?.employeeSheetFinalRow?.role||d?.employeeSheetFinalRow?.position)}
function tipRosterFromBatches(batches){
  const out=[];
  for(const b of batches||[]){const date=txt(b.date||b.id);if(!date||date<state.from||date>state.to)continue;const team=Array.isArray(b.team)?b.team:Object.values(b.team&&typeof b.team==='object'?b.team:{}),seen=new Set();
    for(const member of team){const name=normName(typeof member==='string'?member:(member?.name||member?.employee||member?.server));if(!name)continue;const role=batchMemberRole(b,name,typeof member==='object'?member:null);if(role&&!/server/i.test(role))continue;/* Unknown role is retained only if Board also knows this identity. */const c=canonical(name),boardKnown=state.boardRoster.some(x=>x.server===c);if(!role&&!boardKnown)continue;const key=idKey(c);if(seen.has(key))continue;seen.add(key);out.push({date,server:c,rawServer:name,role:role||'Server',source:'TIP TEAM'})}
    for(const [name,d] of Object.entries(b.drafts||{})){const n=normName(name);if(!n)continue;const role=batchMemberRole(b,n,null);if(role&&!/server/i.test(role))continue;const c=canonical(n),boardKnown=state.boardRoster.some(x=>x.server===c);if(!role&&!boardKnown)continue;const key=idKey(c);if(seen.has(key))continue;seen.add(key);out.push({date,server:c,rawServer:n,role:role||'Server',source:'TIP DRAFT'})}
  }
  return out;
}
function updateTipStatus(){const el=$('tipStatus');if(!el)return;if(tipFeed.error&&!(tipFeed.reports||tipFeed.batches))el.textContent='ERROR';else if(tipFeed.reports&&tipFeed.batches)el.textContent='LIVE';else if(tipFeed.reports||tipFeed.batches)el.textContent='PARTIAL';else el.textContent='SYNCING'}
async function refreshBoard(){try{$('boardStatus').textContent='SYNCING';const [arc,boards,teamDays]=await Promise.all([fetchJson(BOARD_ROOT+'/analyticsV1.json'),fetchJson(BOARD_ROOT+'/rotationBoardV31.json'),fetchJson(BOARD_ROOT+'/teamDayV1.json').catch(()=>null)]);const events=[],roster=[];for(const d of dateList(state.from,state.to)){roster.push(...boardTeamRoster(teamDays?.[d],d));for(const sh of ['AM','PM']){if(state.shift!=='ALL'&&state.shift!==sh)continue;const key=d+'_'+sh,live=boards?.[key],a=arc?.[key];if(live)roster.push(...boardRosterFromBoard(live,d,sh));const liveEv=live?boardEvents(live,d,sh):[];if(liveEv.length)events.push(...liveEv);else if(a)events.push(...archiveEvents(a))}}state.board=events;state.boardRoster=dedupeRoster(roster);state.tipRoster=tipRosterFromBatches(state.batches);$('boardStatus').textContent='LIVE';rebuild()}catch(e){console.error(e);$('boardStatus').textContent='ERROR';rebuild()}}
function subscribeTips(){for(const u of tipUnsubs){try{u()}catch(e){}}tipUnsubs=[];tipFeed={reports:false,batches:false,error:false};updateTipStatus();if(!auth.currentUser||!profile)return;try{const qr=query(collection(db,'hourlyReports'),where('date','>=',state.from),where('date','<=',state.to));tipUnsubs.push(onSnapshot(qr,s=>{state.tips=s.docs.map(d=>({id:d.id,...d.data()}));tipFeed.reports=true;updateTipStatus();rebuild()},e=>{console.error(e);tipFeed.error=true;updateTipStatus()}));const qb=query(collection(db,'hourlyV1Batches'),where('date','>=',state.from),where('date','<=',state.to));tipUnsubs.push(onSnapshot(qb,s=>{state.batches=s.docs.map(d=>({id:d.id,...d.data()}));state.tipRoster=tipRosterFromBatches(state.batches);tipFeed.batches=true;updateTipStatus();rebuild()},e=>{console.warn('Tip team roster feed unavailable:',e);tipFeed.error=true;updateTipStatus()}))}catch(e){console.error(e);tipFeed.error=true;updateTipStatus()}}
function reportHours(r){return num(r.totalHoursWork??r.totalHours??r.hoursWorked??r.hours?.totalHours??0)}
function shiftBucket(r){const s=txt(r.shift).toUpperCase();if(s.includes('AM')&&!s.includes('PM')&&!s.includes('DOUBLE'))return 'AM';if(s==='PM')return 'PM';return 'ALL'}
function reportSales(r){return num(r.grandTotal)}
function reportTip(r){return num(r.grandTotalTip??(num(r.paidTip)+num(r.cashTip)))}
function reportPayout(r){return num(r.totalPaidOut??r.grandTotalAfterAdjustment??r.finalPaidOut)}
function reportBusser(r){return num(r.busserTipOut??r.busserTotal??num(r.busserTipOutAM)+num(r.busserTipOutPM))}
function reportBarOut(r){return num(r.barTipOut??r.totalBarTipOut??num(r.barTipOutAM)+num(r.barTipOut24)+num(r.barTipOutPM))}
function reportBarIn(r){return num(r.bartenderBarTipReceived??r.barTipReceived??num(r.barTipReceivedAM)+num(r.barTipReceived24)+num(r.barTipReceivedPM))}
function quantileScore(vals,v){const a=vals.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;let le=0;for(const x of a)if(x<=v)le++;return le/a.length*100}
function medianGap(events){const t=events.map(e=>num(e.seatedAt)).filter(Boolean).sort((a,b)=>a-b);if(t.length<2)return 0;const gaps=[];for(let i=1;i<t.length;i++){const m=(t[i]-t[i-1])/60000;if(m>0&&m<240)gaps.push(m)}gaps.sort((a,b)=>a-b);if(!gaps.length)return 0;const m=Math.floor(gaps.length/2);return gaps.length%2?gaps[m]:(gaps[m-1]+gaps[m])/2}
function buildRows(){
 const map=new Map(),get=(n,meta={})=>{n=canonical(n);if(!map.has(n))map.set(n,{name:n,active:isActiveName(n),events:[],reports:[],tables:0,guests:0,rotation:0,hours:0,sales:0,paidTip:0,cashTip:0,tipIncome:0,payout:0,busser:0,barOut:0,barIn:0,days:new Set(),am:0,pm:0,sources:new Set(),aliases:new Set(),scheduled:false});const x=map.get(n);if(meta.source)x.sources.add(meta.source);if(meta.raw)x.aliases.add(meta.raw);if(meta.scheduled)x.scheduled=true;if(meta.date)x.days.add(meta.date);return x};
 state.boardRoster.forEach(r=>get(r.server,{source:r.source||'BOARD ROSTER',raw:r.rawServer,scheduled:true,date:r.date}));
 state.tipRoster.forEach(r=>get(r.server,{source:r.source||'TIP TEAM',raw:r.rawServer,scheduled:true,date:r.date}));
 state.board.forEach(e=>{const x=get(e.server,{source:'BOARD',raw:e.rawServer,date:e.date});x.events.push(e);x.tables++;x.guests+=num(e.people);x.rotation+=num(e.rotationSlots);x.days.add(e.date);if(e.shift==='AM')x.am++;if(e.shift==='PM')x.pm++});
 const boardIds=new Set(state.boardRoster.map(r=>r.server));
 state.tips.forEach(r=>{if(state.shift!=='ALL'&&shiftBucket(r)!=='ALL'&&shiftBucket(r)!==state.shift)return;const n=reportName(r);if(!n)return;const c=canonical(n),pos=reportPosition(r);if(pos&&!/server/i.test(pos))return;if(!pos&&!boardIds.has(c))return;const x=get(c,{source:'TIP REPORT',raw:n,date:r.date});x.reports.push(r);x.days.add(r.date);x.hours+=reportHours(r);x.sales+=reportSales(r);x.paidTip+=num(r.paidTip);x.cashTip+=num(r.cashTip);x.tipIncome+=reportTip(r);x.payout+=reportPayout(r);x.busser+=reportBusser(r);x.barOut+=reportBarOut(r);x.barIn+=reportBarIn(r)});
 const rows=[...map.values()];rows.forEach(x=>{x.daysCount=x.days.size;x.avgParty=x.tables?x.guests/x.tables:0;x.salesPerGuest=x.guests?x.sales/x.guests:0;x.salesPerTable=x.tables?x.sales/x.tables:0;x.tablesPerHour=x.hours?x.tables/x.hours:0;x.guestsPerHour=x.hours?x.guests/x.hours:0;x.salesPerHour=x.hours?x.sales/x.hours:0;x.tipPerHour=x.hours?x.tipIncome/x.hours:0;x.tipPct=x.sales?x.tipIncome/x.sales*100:0;x.medianSeatGap=medianGap(x.events);x.rotationGuestEfficiency=x.rotation?x.guests/x.rotation:0;x.hasPerformance=!!(x.tables||x.guests||x.hours||x.sales||x.tipIncome)});
 const eligible=rows.filter(x=>x.hasPerformance);for(const x of rows){x.overall=x.hasPerformance?Math.round(.30*quantileScore(eligible.map(r=>r.salesPerHour),x.salesPerHour)+.22*quantileScore(eligible.map(r=>r.guestsPerHour),x.guestsPerHour)+.18*quantileScore(eligible.map(r=>r.tablesPerHour),x.tablesPerHour)+.15*quantileScore(eligible.map(r=>r.salesPerGuest),x.salesPerGuest)+.15*quantileScore(eligible.map(r=>r.tipPerHour),x.tipPerHour)):null}
 return rows.sort((a,b)=>(b.hasPerformance-a.hasPerformance)||num(b.overall)-num(a.overall)||b.sales-a.sales||a.name.localeCompare(b.name))
}
function totals(rows){return rows.reduce((a,x)=>{a.tables+=x.tables;a.guests+=x.guests;a.rotation+=x.rotation;a.hours+=x.hours;a.sales+=x.sales;a.tip+=x.tipIncome;a.payout+=x.payout;return a},{tables:0,guests:0,rotation:0,hours:0,sales:0,tip:0,payout:0})}
function rebuild(){state.rows=buildRows();state.rawNames=[...new Set([...state.board.map(e=>e.rawServer),...state.boardRoster.map(r=>r.rawServer),...state.tipRoster.map(r=>r.rawServer),...state.tips.map(r=>reportName(r)).filter(Boolean)])].filter(Boolean).sort();$('updatedAt').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});renderKpis();renderContent()}
function renderKpis(){const t=totals(state.rows);$('kpis').innerHTML=[['Tables',t.tables,'Board seatings'],['Guests',t.guests,t.tables?n1(t.guests/t.tables)+' avg party':'—'],['Sales',money(t.sales),t.guests?money(t.sales/t.guests)+' / guest':'—'],['Hours',n1(t.hours),state.rows.length+' servers'],['Tip Income',money(t.tip),t.sales?n1(t.tip/t.sales*100)+'% of sales':'—'],['Paid Out',money(t.payout),'Final report value']].map(x=>`<div class="kpi"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}
function rowTable(rows=state.rows){let rank=0;return `<div class="tablewrap"><table><thead><tr><th>Server</th><th>Overall</th><th>Days</th><th>Hours</th><th>Tables</th><th>Guests</th><th>Rotation</th><th>Sales</th><th>Tip</th><th>Sales/Hr</th><th>Guests/Hr</th><th>Tables/Hr</th><th>Sales/Guest</th><th>Median Seat Gap</th></tr></thead><tbody>${rows.map(x=>{const rn=x.hasPerformance?++rank:'—';return `<tr class="clickrow" data-server="${esc(x.name)}"><td><span class="rank">${rn}</span><b>${esc(x.name)}</b>${x.active?'':' <span class="tag">INACTIVE</span>'}${!x.hasPerformance?' <span class="tag">ROSTER</span>':''}</td><td><b>${x.overall==null?'—':x.overall}</b></td><td>${x.daysCount}</td><td>${n1(x.hours)}</td><td>${x.tables}</td><td>${x.guests}</td><td>${x.rotation}</td><td>${money(x.sales)}</td><td>${money(x.tipIncome)}</td><td>${x.hours?money(x.salesPerHour):'—'}</td><td>${x.hours?n1(x.guestsPerHour):'—'}</td><td>${x.hours?n1(x.tablesPerHour):'—'}</td><td>${x.guests?money(x.salesPerGuest):'—'}</td><td>${x.medianSeatGap?n1(x.medianSeatGap)+' min':'—'}</td></tr>`}).join('')}</tbody></table></div>`}
function bars(title,rows,key,format=v=>n1(v)){const pool=rows.filter(x=>key==='overall'?x.overall!=null:x.hasPerformance),a=[...pool].sort((x,y)=>num(y[key])-num(x[key])).slice(0,12),mx=Math.max(1,...a.map(x=>num(x[key])));return `<div class="card"><div class="section-title"><h2>${title}</h2><small>Top ${a.length}</small></div>${a.map((x,i)=>`<div class="barrow"><span>${i+1}. ${esc(x.name)}</span><div class="bartrack"><i style="width:${Math.max(2,num(x[key])/mx*100)}%"></i></div><b style="text-align:right">${format(x[key])}</b></div>`).join('')||'<p class="muted">No performance data yet.</p>'}</div>`}
function renderContent(){const c=$('content'),r=state.rows;if(state.tab==='overview'){c.innerHTML=`<div class="grid2">${bars('Overall Performance Index',r,'overall')}${bars('Sales per Hour',r,'salesPerHour',money)}</div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Server Summary</h2><small>${state.from} → ${state.to}</small></div>${rowTable()}</div><div class="notice" style="margin-top:14px"><b>Overall Index formula:</b> 30% Sales/Hour + 22% Guests/Hour + 18% Tables/Hour + 15% Sales/Guest + 15% Tip Income/Hour. Percentile-based within the selected period. It is a management comparison index, not a disciplinary score.</div>`}else if(state.tab==='ranking'){c.innerHTML=`<div class="grid2">${bars('Most Sales',r,'sales',money)}${bars('Most Guests',r,'guests')}${bars('Most Tables',r,'tables')}${bars('Most Tip Income',r,'tipIncome',money)}</div><div class="card" style="margin-top:14px">${rowTable()}</div>`}else if(state.tab==='rotation'){c.innerHTML=`<div class="grid2">${bars('Tables per Hour',r,'tablesPerHour')}${bars('Guests per Hour',r,'guestsPerHour')}${bars('Rotation Turns Used',r,'rotation')}${bars('Guests per Rotation Turn',r,'rotationGuestEfficiency')}</div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Rotation & Pace Detail</h2><small>Median gap = time between seating events, not service duration.</small></div>${rowTable([...r].sort((a,b)=>b.guestsPerHour-a.guestsPerHour))}</div>`}else if(state.tab==='finance'){c.innerHTML=`<div class="grid2">${bars('Sales per Guest',r,'salesPerGuest',money)}${bars('Sales per Table',r,'salesPerTable',money)}${bars('Tip Income per Hour',r,'tipPerHour',money)}${bars('Final Paid Out',r,'payout',money)}</div><div class="card" style="margin-top:14px">${rowTable([...r].sort((a,b)=>b.sales-a.sales))}</div>`}else{renderTables(c)}bindRows()}
function renderTables(c){const map=new Map();state.board.forEach(e=>{if(!map.has(e.table))map.set(e.table,{table:e.table,seatings:0,guests:0,servers:new Map()});const x=map.get(e.table);x.seatings++;x.guests+=e.people;x.servers.set(e.server,(x.servers.get(e.server)||0)+1)});const a=[...map.values()].sort((x,y)=>y.seatings-x.seatings);c.innerHTML=`<div class="card"><div class="section-title"><h2>Table Utilization</h2><small>Selected period</small></div><div class="tablewrap"><table><thead><tr><th>Table</th><th>Seatings</th><th>Guests</th><th>Avg Party</th><th>Most Frequent Server</th></tr></thead><tbody>${a.map(x=>{const top=[...x.servers].sort((p,q)=>q[1]-p[1])[0];return `<tr><td><b>${esc(x.table)}</b></td><td>${x.seatings}</td><td>${x.guests}</td><td>${n1(x.guests/x.seatings)}</td><td>${top?esc(top[0])+' ('+top[1]+')':'—'}</td></tr>`}).join('')}</tbody></table></div></div>`}
function bindRows(){document.querySelectorAll('[data-server]').forEach(tr=>tr.onclick=()=>openServer(tr.dataset.server))}
function openServer(name){const x=state.rows.find(r=>r.name===name);if(!x)return;$('modalTitle').textContent=name+' • Server Detail';const events=[...x.events].sort((a,b)=>(a.date+a.shift).localeCompare(b.date+b.shift)||a.seatedAt-b.seatedAt);$('modalBody').innerHTML=`<div class="kpis"><div class="kpi"><span>Overall Index</span><b>${x.overall==null?'—':x.overall}</b></div><div class="kpi"><span>Tables</span><b>${x.tables}</b></div><div class="kpi"><span>Guests</span><b>${x.guests}</b></div><div class="kpi"><span>Sales</span><b>${money(x.sales)}</b></div><div class="kpi"><span>Tip Income</span><b>${money(x.tipIncome)}</b></div><div class="kpi"><span>Hours</span><b>${n1(x.hours)}</b></div></div><div class="card" style="margin-bottom:14px"><b>Identity:</b> ${[...x.aliases].map(esc).join(' • ')||esc(x.name)} &nbsp; <span class="tag">${[...x.sources].map(esc).join(' • ')||'ROSTER'}</span></div><div class="grid2"><div class="card"><h3>Efficiency</h3><p>Sales / Hour: <b>${money(x.salesPerHour)}</b></p><p>Guests / Hour: <b>${n1(x.guestsPerHour)}</b></p><p>Tables / Hour: <b>${n1(x.tablesPerHour)}</b></p><p>Sales / Guest: <b>${money(x.salesPerGuest)}</b></p><p>Sales / Table: <b>${money(x.salesPerTable)}</b></p><p>Median seating gap: <b>${x.medianSeatGap?n1(x.medianSeatGap)+' min':'—'}</b></p></div><div class="card"><h3>Tip & Distribution</h3><p>Paid Tip: <b>${money(x.paidTip)}</b></p><p>Cash Tip: <b>${money(x.cashTip)}</b></p><p>Tip Income: <b>${money(x.tipIncome)}</b></p><p>Busser Tip Out: <b>${money(x.busser)}</b></p><p>Bar Tip Out: <b>${money(x.barOut)}</b></p><p>Bar Tip Received: <b>${money(x.barIn)}</b></p><p>Final Paid Out: <b>${money(x.payout)}</b></p></div></div><div class="card" style="margin-top:14px"><h3>Seating History</h3><div class="tablewrap"><table><thead><tr><th>Date</th><th>Shift</th><th>Time</th><th>Table</th><th>Guests</th><th>Section</th><th>Rotation Slots</th><th>Source</th></tr></thead><tbody>${events.map(e=>`<tr><td>${e.date}</td><td>${e.shift}</td><td>${e.seatedAt?new Date(e.seatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'}</td><td>${esc(e.table)}</td><td>${e.people}</td><td>${esc(e.section)}</td><td>${e.rotationSlots}</td><td>${e.source}</td></tr>`).join('')}</tbody></table></div></div>`;$('modal').classList.remove('hidden')}

function identityModal(){const groups=new Map();state.rawNames.forEach(n=>{const c=canonical(n);if(!groups.has(c))groups.set(c,[]);groups.get(c).push(n)});$('modalTitle').textContent='Employee Identity Sync';$('modalBody').innerHTML=`<p class="muted">Merge different Board/Tip names into one analytics identity. Source apps are never rewritten.</p><div class="aliasgrid">${[...groups].sort().map(([c,aliases])=>`<div class="aliasitem"><div><b>${esc(c)}</b><div class="muted">${aliases.map(esc).join(' • ')}</div></div><span class="tag">${isActiveName(c)?'ACTIVE':'INACTIVE'}</span></div>`).join('')}</div><div class="card" style="margin-top:14px"><h3>Merge / Rename</h3><div class="grid2"><div class="field"><label>Source name / alias</label><select id="aliasSource">${state.rawNames.map(n=>`<option>${esc(n)}</option>`).join('')}</select></div><div class="field"><label>Canonical employee name</label><input id="aliasCanonical" placeholder="Example: Ariana Garner"></div></div><div style="display:flex;gap:8px;margin-top:10px"><button class="btn primary" id="mergeAlias">Save Alias</button><button class="btn" id="toggleInactive">Toggle Active / Inactive</button><button class="btn red" id="resetAliases">Reset Defaults</button></div></div>`;$('modal').classList.remove('hidden');$('mergeAlias').onclick=()=>{const s=$('aliasSource').value,c=normName($('aliasCanonical').value);if(!s||!c)return alert('Choose source name and canonical name.');identity[idKey(s)]={canonical:c,active:identity[idKey(s)]?.active!==false};identity[idKey(c)]={canonical:c,active:identity[idKey(c)]?.active!==false};saveIdentity();refreshBoard();identityModal()};$('toggleInactive').onclick=()=>{const s=$('aliasSource').value,c=canonical(s),active=isActiveName(c);Object.keys(identity).forEach(k=>{if(identity[k].canonical===c)identity[k].active=!active});identity[idKey(c)]={canonical:c,active:!active};saveIdentity();rebuild();identityModal()};$('resetAliases').onclick=()=>{if(confirm('Reset identity aliases to app defaults?')){localStorage.removeItem('fzsi_identity_v11');localStorage.removeItem('fzsi_identity_v1');identity=loadIdentity();saveIdentity();rebuild();identityModal()}}}

function pdfReport(lang='EN'){const J=window.jspdf?.jsPDF;if(!J)return alert('PDF library is unavailable. Check internet connection.');const id=lang==='ID',d=new J({orientation:'landscape',unit:'pt',format:'letter'}),t=totals(state.rows),title=id?'LAPORAN ANALISA SERVER':'SERVER ANALYTICS REPORT',sub=`${state.from} - ${state.to} • ${state.shift}`;d.setFillColor(7,20,33);d.rect(0,0,792,612,'F');d.setTextColor(255);d.setFont('helvetica','bold');d.setFontSize(20);d.text('FZ SERVER INTELLIGENCE',30,38);d.setFontSize(15);d.text(title,30,63);d.setFont('helvetica','normal');d.setFontSize(9);d.setTextColor(170);d.text(sub,30,80);d.setTextColor(255);d.setFontSize(10);const summary=id?[`Meja: ${t.tables}`,`Tamu: ${t.guests}`,`Penjualan: ${money(t.sales)}`,`Jam Kerja: ${n1(t.hours)}`,`Pendapatan Tip: ${money(t.tip)}`,`Total Dibayar: ${money(t.payout)}`]:[`Tables: ${t.tables}`,`Guests: ${t.guests}`,`Sales: ${money(t.sales)}`,`Hours: ${n1(t.hours)}`,`Tip Income: ${money(t.tip)}`,`Paid Out: ${money(t.payout)}`];d.text(summary.join('    •    '),30,105);const head=id?['#','Server','Index','Hari','Jam','Meja','Tamu','Rotasi','Penjualan','Tip','Sales/Jam','Tamu/Jam','Meja/Jam','Sales/Tamu']:['#','Server','Index','Days','Hours','Tables','Guests','Rotation','Sales','Tip','Sales/Hr','Guests/Hr','Tables/Hr','Sales/Guest'];let pr=0;const body=state.rows.map(x=>[x.hasPerformance?++pr:'—',x.name,x.overall==null?'—':x.overall,x.daysCount,n1(x.hours),x.tables,x.guests,x.rotation,money(x.sales),money(x.tipIncome),x.hours?money(x.salesPerHour):'—',x.hours?n1(x.guestsPerHour):'—',x.hours?n1(x.tablesPerHour):'—',x.guests?money(x.salesPerGuest):'—']);d.autoTable({startY:125,head:[head],body,theme:'grid',styles:{fontSize:6.8,cellPadding:3,textColor:[20,35,50]},headStyles:{fillColor:[12,69,92],textColor:255},alternateRowStyles:{fillColor:[236,245,249]}});let y=d.lastAutoTable.finalY+16;if(y>535){d.addPage();y=35}d.setTextColor(255);d.setFont('helvetica','bold');d.setFontSize(9);d.text(id?'CATATAN METRIK':'METRIC NOTES',30,y);d.setFont('helvetica','normal');d.setTextColor(190);d.setFontSize(7);const note=id?'Overall Performance Index = 30% Sales/Jam + 22% Tamu/Jam + 18% Meja/Jam + 15% Sales/Tamu + 15% Pendapatan Tip/Jam. Kecepatan = throughput/seating pace; bukan durasi pelayanan meja.':'Overall Performance Index = 30% Sales/Hour + 22% Guests/Hour + 18% Tables/Hour + 15% Sales/Guest + 15% Tip Income/Hour. Pace measures throughput/seating pace, not table service duration.';d.text(d.splitTextToSize(note,730),30,y+13);d.save(`FZ_Server_Intelligence_${lang}_${state.from}_${state.to}.pdf`)}
function pdfMenu(){$('modalTitle').textContent='Download PDF';$('modalBody').innerHTML=`<div class="grid2"><button class="btn primary" id="pdfEN" style="padding:28px">English PDF</button><button class="btn gold" id="pdfID" style="padding:28px">PDF Bahasa Indonesia</button></div><p class="muted">Includes executive summary, server ranking, sales/tip/pace metrics, and transparent scoring formula.</p>`;$('modal').classList.remove('hidden');$('pdfEN').onclick=()=>pdfReport('EN');$('pdfID').onclick=()=>pdfReport('ID')}

$('loginBtn').onclick=async()=>{const u=$('user').value.trim(),p=$('pass').value;if(!u||!p)return $('loginMsg').textContent='Enter owner username and password.';try{$('loginMsg').textContent='Signing in…';await signInWithEmailAndPassword(auth,emailFor(u),p)}catch(e){$('loginMsg').textContent='Login failed: '+(e.code||e.message)}};
$('pass').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});
onAuthStateChanged(auth,async user=>{if(!user){profile=null;$('loginView').classList.remove('hidden');$('app').classList.add('hidden');return}const s=await getDoc(doc(db,'users',user.uid));const p=s.exists()?s.data():null;if(!p||p.active===false||p.role!=='owner'){await signOut(auth);$('loginMsg').textContent='Owner account required.';return}profile=p;$('ownerName').textContent=p.displayName||p.username||'OWNER';$('loginView').classList.add('hidden');$('app').classList.remove('hidden');setMode('daily');if(timer)clearInterval(timer);timer=setInterval(refreshBoard,30000)});
$('logoutBtn').onclick=()=>signOut(auth);$('refreshBtn').onclick=()=>{state.from=$('from').value;state.to=$('to').value;state.shift=$('shift').value;subscribeTips();refreshBoard()};$('aliasBtn').onclick=identityModal;$('pdfBtn').onclick=pdfMenu;$('modalClose').onclick=()=>$('modal').classList.add('hidden');$('modal').addEventListener('click',e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x===b));renderContent()});$('shift').onchange=()=>{state.shift=$('shift').value};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
